[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-eboda17
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-eboda17
GtkTheme=oomox-eboda17
IconTheme=oomox-eboda17
MetacityTheme=oomox-eboda17
